name: PYPACKAGE
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python==3.11
  - numpy
  - pandas
  - pydantic
  - pytest
  - psycopg2
  - sqlalchemy
  - fastapi
  - fastapi-users-db-sqlalchemy
  - uvicorn
  - pip:
    - llama-index
    - llama-index-llms-llama-cpp
    - llama-index-embeddings-huggingface
