name: pubmed search and store in db

on:
  schedule:
    - cron: '0 0 1 * *' # every 1st of the month
  workflow_dispatch:

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/jobs:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/jobs:latest


jobs:
  query_pubmed:
    runs-on: ubuntu-latest
    name: Query Pubmed
    env:
      KMP_DUPLICATE_LIB_OK: TRUE
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ./services/backend/
          load: true
          tags: ${{ env.TEST_TAG }}
          file: ./services/backend/db.Dockerfile
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./services/backend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
          file: ./services/backend/db.Dockerfile
